module.exports = {
  default:                          'Default',
  alliance:                         [ 'Alliance', 'Normal', 'Rainy' ],
  antiquity:                        'Antiquity',
  armory:                           'Armory', // Not in game; used for MLG Stronghold HUD
  zodiac_hud:                       'Azure Constellation',
  bts_summit:                       'Beyond the Summit',
  black_monolith:                   'Black Monolith',
  brawl_basher:                     'Brawl Basher',
  brewery:                          'Brewery',
  tarantula:                        'Brood Hunter',
  hud_chaosknight:                  'Chaos Knight (?)', // Not in game?
  diretide:                         'Cruel Diretide',
  crystalmana:                      'Crystallized Mana',
  curiosity_hud:                    'Curiosity',
  d2cls5_hud:                       'D2CL Season 5',
  cold_depths:                      'Deepest Depths',
  demonichud:                       'Demonic Essence',
  free_to_play:                     'Depth of Field',
  detonation:                       'Detonation',
  weplay:                           'Dim Forest',
  dire:                             'Direstone',
  diretide2013:                     'Diretide (2013)', // Not in game?
  donbass_cup_hud:                  'DonBass Cup Season 3',
  _hud_skin__donbass_cup:           'DonBass Cup Season 3 (Copy)',
  dac_2015:                         'Dota 2 Asia Championship',
  dc_dayhud:                        [ 'DotaCinema', 'Dark', 'Bright' ],
  dragon_scale:                     'Dragon Scale',
  driftwood:                        'Driftwood',
  hud_driftwood:                    'Driftwood (?)', // Copy of Driftwood?
  dark_forest:                      'Elder Bark',
  empower:                          'Empowered',
  esl_one_hud_fortress:             'ESL One Fortress',
  eswc_diamond:                     'ESWC Diamond',
  evil_genius_hud:                  'Evil Geniuses',
  familiar_woods:                   [ 'Familiar Woods', 'Woodsy', 'Shagbark!' ],
  force_of_spirit:                  'Force of Spirit',
  frozen_touch:                     'Frozen Touch',
  ferocious:                        'Furnace',
  gear_tooth:                       'Gear Tooth',
  ghostly_silence:                  'Ghostly Silence',
  golden_treasures:                 'Golden Treasures',
  green_ural:                       'Green Ural',
  dotapit_s3_hud:                   'Hearth of the Pit',
  hellfire:                         'Hellfire',
  fireborn_hud:                     [ 'HUD of the Burning Scale', 'Default', 'Poison', 'Fire', 'Ice' ],
  dancing_butterfly_loading_screen: 'i-League Season 2',
  spirit_stones:                    'Imbued Stone',
  the_international_2015:           'The International 2015 HUD',
  the_international_2016:           'The International 2016 HUD',
  iron_cage:                        'Iron Cage',
  iron_thorn:                       'Iron Thorn',
  jollyroger:                       [ 'Jolly Roger', 'Davy Jones', 'Landlubber' ],
  jungle_ruin:                      'Jungle Ruin',
  livingindarkness:                 'Living in Darkness',
  menace:                           'Malice',
  mana_pool:                        'Mana Pool',
  bane_delirium:                    'Midnight Terror',
  stronghold:                       'MLG Stronghold',
  nature:                           'Nature',
  necropolis:                       'Necropolis',
  new_bloom:                        'New Bloom',
  od:                               'Omen',
  portal:                           'Portal',
  power_surge:                      'Power Surge (?)', // Copy of Surge?
  starladder:                       'Powered Star',
  radiantentity:                    'Radiant Entity',
  radiant:                          'Radiant Ore',
  redwarrior_hud:                   'Red Warrior',
  eslbrazil_hud:                    'Rei da Mesa',
  'reign_of_maelrawn_hud_-_fgcl':   'Reign of Maelrawn',
  royal_crypt_hud:                  'Royal Crypt',
  sample:                           'Sample (?)', // Unused?
  hud_sandsofluxor:                 'Sands of Luxor',
  dreamleague:                      [ 'Scions of the Sky', null, 'Alternative Style' ],
  sltvx:                            'SLTV Star Series X',
  winter:                           'Snows of Frostivus',
  hud_springessence:                'Spring Essence',
  premier_league:                   'Stone Ruin',
  bts3_hud:                         'The Summit 3',
  esp_surge_hud:                    'Surge',
  team_empire_hud:                  'Team Empire',
  techlabs2014:                     'Techlabs Moscow Cup 2014',
  crystal_wings:                    'Tempest Wing',
  temple_wall:                      'Temple',
  sacredmemories_hud:               'Temple of the Sacred Memories',
  three_virtues:                    'Three Virtues',
  thunder_spirit:                   'Thunder Spirit',
  timber_fury:                      'Timber Fury',
  titan_hud:                        'Titan',
  undying_hud:                      'Tombstone',
  quake:                            'Tremor',
  ti4:                              'Triumph',
  underwater:                       'Underwater',
  ti3:                              'Valor',
  steelseries_bamboo:               'Vermilion',
  vici_gaming:                      'ViCi Gaming',
  virtus_pro:                       'Virtus.Pro',
  guardian_angel:                   'Winged Guardian',
  workshop_ingame_test:             'Workshop In-Game Test (?)', // Unused?
};
